### PR TITLE
Make json-2-csv promisifiable

### PR DESCRIPTION
**Pull request by mrodrig**
Fixing #14

### CODE REVIEW

**Comment by spxis** [comment]
This was an excellent commit. Works great btw.

**Comment by shahzeb1** [comment]
Hmm... why isn't this function available when installed using npm?
image

**Comment by mrodrig** [comment]
Hi @shahzeb1. This PR was intended to allow the module to work when promisified with another module, such as `bluebird`.  Here's an example of how it can be promisified:

```javascript
var promise = require('bluebird'),
    converter = promise.promisifyAll(require('json-2-csv'));

var options = {
    KEYS : ['info.name', 'year']
};

var documents = [
    {
        "info": {
            "name": "Mike"
        },
        "coursesTaken": ["CS2500", "CS2510"],
        "year": "Sophomore"
    },
    {
        "info": {
            "name": "John"
        },
        "coursesTaken": ["ANTH1101", "POL2312", "MATH2142", "POL3305", "LAW2100"],
        "year": "Senior"
    }
];

converter.json2csvAsync(documents, options)
  .then(function (csv) { console.log(csv); })
  .catch(function (err) { throw err; });
```

In the future, I may add the promisified versions of the functions to the module, but at the time didn't want to add an additional dependency.  My thought was that if a developer wants to use the promisified version, they probably already have a promise library pulled into the project that can promisify the necessary function(s).

**Comment by shahzeb1** [comment]
Ah ok gotchu. Thank you. Would be neat to make it so that it is `promise`-fied right out of the box. 

Would you be interested in this as a PR?

**Comment by mrodrig** [comment]
Hi @shahzeb1. Sorry for not getting back to you on this. At the time, I forgot that I was already pulling the `bluebird` module in, but version `2.2.0` will now include the `json2csvPromisified` and `csv2jsonPromisified` functions which will provide the same functionality, but promisified right out of the box. Thanks!

**Pull request merged**
