### PR TITLE
Add 'useLocaleFormat' option.

### PR DESCRIPTION
**Pull request by mrodrig**
## Background Information

- Fixes issue(s): #146, #64 
- Proposed release version: `3.7.0`

I have...
- [x] added at least one test to verify the failure condition is fixed.
- [x] verified the tests are passing.

### CODE REVIEW

**Comment by Rjrunner44** [comment]
I'm not sure this is working, whether I set useLocaleFormat true or false, the same date-time string comes out (just without the (timezone info annotation) part of it, but the input date I have in the DB Is UTC, and what comes out (again in both cases) is local time. What I'd really like is just to get my date-time back out in proper ISO8601 Z format like I sent it in...e.g. "2020-11-24T17:48:09.365Z"

**Comment by mrodrig** [comment]
Hi @Rjrunner44. Thanks for mentioning that. It looks like it is working...

`useLocaleFormat: false`:
```
Make,Model,Year,Production,Specifications.Mileage,Specifications.Trim
Nissan,Murano,2013,Tue Mar 12 2013 00:00:00 GMT-0400 (Eastern Daylight Time),7106,S AWD
BMW,X5,2014,Tue Aug 20 2013 00:00:00 GMT-0400 (Eastern Daylight Time),3287,M
```

`useLocaleFormat: true`
```
Make,Model,Year,Production,Specifications.Mileage,Specifications.Trim
Nissan,Murano,2013,"3/12/2013, 12:00:00 AM",7106,S AWD
BMW,X5,2014,"8/20/2013, 12:00:00 AM",3287,M
```

... but it doesn't seem like that option is what you need. There currently isn't an option that can be passed in to make dates be "stringified" in ISO format, but that should be a pretty simple addition, if you think that would be helpful and still need the functionality. The `useLocaleFormat` option just causes certain values to be "stringified" with `toLocaleString` instead, but that unfortunately won't convert dates into ISO format. Let me know if you're still interested in this functionality and I can see about getting it added into the next release.

Thanks!

**Comment by Rjrunner44** [comment]
Cool. Maybe I was looking at the dates wrong here...i'll have another look. Sometimes I read dates wrong 🤪  

useLocaleFormat: false => "Fri Nov 27 2020 18:44:20 GMT+0000 (Coordinated Universal Time)"
useLocaleFormat: true => "11/27/2020, 6:44:20 PM"

Yes, if you're still updating code, something like:

useIso8601Format: true => "2020-11-27T18:44:20.331Z"

would be helpful, as that's the format I have to use.

**Comment by Rjrunner44** [comment]
`function recordFieldValueToString(fieldValue) {
        if (Array.isArray(fieldValue) || utils.isObject(fieldValue) && !utils.isDate(fieldValue)) {
            return JSON.stringify(fieldValue);
        } else if (utils.isUndefined(fieldValue)) {
            return 'undefined';
        } else if (utils.isNull(fieldValue)) {
            return 'null';
        } else {
            if (utils.isDate(fieldValue) && options.useDateIso8601Format) {
                return new Date(fieldValue).toISOString();
            } else {
                return !options.useLocaleFormat ? fieldValue.toString() : fieldValue.toLocaleString();
            }
        }
    }`

**Pull request merged**
